<a href="https://colab.research.google.com/github/Tatthangnha/TH_DeepLearning/blob/main/buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [4]:
import numpy as np

my_list=[1,3,8,9,20]
print("Python list: ",my_list)

my_numpy_array= np.array( my_list)
print("Numpy array: ",my_numpy_array)

a=np.array([1,9,3,8,6,4])
print(a)

Python list:  [1, 3, 8, 9, 20]
Numpy array:  [ 1  3  8  9 20]
[1 9 3 8 6 4]


In [5]:
c=np.array([(1,2,3),
          (4,5,6)])
print(c)
print(c.shape)
print(c.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [6]:
d=np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[ 7., 8., 9.], [ 10, 11, 12]]
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]
(2, 2, 3)


In [8]:
e=np.zeros((2, 2))
f=np.ones((3, 3))
print('Zero matrix:\n', e)
print('One matrix\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
e=np.array([[1., 2., 3.], [4.,5.,6.]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)

g= np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[ 7., 8., 9.], [ 10, 11, 12]]
])
print(g)
print(g.shape)
h=g.reshape(3,4)
print('reshape (3, 4)\n', h)
j=g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)
k=g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)




[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  6.  7.]
 [ 8.  9. 10. 11.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 6.  7.]
  [ 8.  9.]
  [10. 11.]]]


In [15]:
e =np.array([[1., 2., 3.], [4.,5.,6.]])
f=e.flatten()
print(f)
g= np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[ 7., 8., 9.], [ 10, 11, 12]]
])
j=g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [16]:
f=np.array([1.,2.,3.])
g=np.array([4.,5.,6.])
h_stack=np.hstack((f,g))
print('Horizontal Append\n', h_stack)
v_stack=np.vstack((f,g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [18]:
a=np.random.randint(100,size=(5,))
print('Random 1-D array\n',a)
b=np.random.randint(100,size=(3,4))
print('Random 2-D array\n',b)
c=np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n',c)

Random 1-D array
 [36 60 60 71 32]
Random 2-D array
 [[69 98 23 95]
 [12 86 73 84]
 [45 36 84 34]]
Random 3-D array
 [[[40 45 78]
  [ 5 93 70]
  [28 22 23]
  [ 9 32 70]]

 [[32 49 66]
  [53 64 19]
  [80 23 44]
  [53 94 56]]

 [[87 61 97]
  [33 59 53]
  [55 17 21]
  [16 15 60]]]


In [19]:
#Sinh mang ngau nhien so that
a=np.random.rand(5)
print('Random 1-D array\n',a)
b=np.random.rand(3,4)
print('Random 2-D array\n',b)
c=np.random.rand(3,4,3)
print('Random 3-D array\n',c)

Random 1-D array
 [0.7950421  0.48670451 0.70676672 0.91059403 0.65419272]
Random 2-D array
 [[0.13817049 0.09193919 0.51311807 0.27691079]
 [0.29297082 0.74509212 0.57972837 0.47481253]
 [0.43635846 0.61992656 0.42265043 0.15632087]]
Random 3-D array
 [[[0.42368233 0.55677572 0.32992212]
  [0.21178065 0.64530766 0.7627755 ]
  [0.74910921 0.15963342 0.84654892]
  [0.40790542 0.42552682 0.68933802]]

 [[0.34058226 0.86448362 0.78193021]
  [0.38169128 0.52625499 0.82153173]
  [0.24487262 0.79176123 0.06150233]
  [0.23608999 0.77300594 0.79285324]]

 [[0.37851115 0.92897016 0.19546769]
  [0.15703458 0.31950803 0.15278303]
  [0.25212416 0.53870062 0.20796947]
  [0.97944151 0.42060676 0.22643053]]]


In [20]:
a=np.random.normal(5, 0.2, 10)
print(a)

[5.31834113 4.85880758 5.08431425 5.0955556  4.91948229 4.91781429
 5.35453483 5.05970093 4.99459128 5.21517127]


In [25]:
#sinh ra mot gia tri ngau nhien tu mang gia tri cho truoc
a=np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)
#sinh ma tran 3 x 5 ngau nhien tu mang gia tri cho truoc
b=np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

4
[[18  6 18 12 18]
 [10  4  2  6 10]
 [18  2  2 12 14]]


In [26]:
A=np.matrix(np.ones((5,5)))
print('The matrix\n', A)
np.array(A)[2]=2
print('Change values of third row with array\n',A)
np.asarray(A)[2]=2
print('Change values of third row with array\n',A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
#tao 20 so nguyen tu 1->n-1
a=np.arange(1, 20)
print(a)
#tao 20 so nguyen tu 1->n-1 moi so tang 2 gia tri
b=np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [28]:
a=np.linspace(1.,5.,num=20)
print(a)

[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


In [33]:
from IPython.display import HTML, display

html_code = """
<div id="pet-container" style="position: relative; width: 100%; height: 100px; overflow: hidden; background-color: #f0f8ff; border-radius: 10px;">
    <img id="pet" src="https://media1.tenor.com/m/2M1Spfnzk3sAAAAd/waving-joy.gif" style="position: absolute; width: 60px; top: 20px; left: 0px;">
</div>

<script>
    let container = document.getElementById('pet-container');
    let pet = document.getElementById('pet');
    let pos = 0;
    let direction = 1;
    let speed = 2; // Tốc độ chạy

    setInterval(function() {
        let width = container.offsetWidth;
        // Đảo chiều nếu đụng tường
        if (pos > width - 60) direction = -1;
        if (pos < 0) direction = 1;

        pos += direction * speed;
        pet.style.left = pos + 'px';

        // Lật ảnh khi quay đầu
        pet.style.transform = direction === -1 ? 'scaleX(-1)' : 'scaleX(1)';
    }, 20); // Tần số làm mới (ms)
</script>
"""

display(HTML(html_code))

In [35]:
#slice
a=np.array([(1,2,3), (4,5,6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])
#indexing
print('Sencond column:', a[:,1])
print('first column:', a[:, 0])
print('First two values of second row:',a[1,:2])


[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Sencond column: [2 5]
first column: [1 4]
First two values of second row: [4 5]


In [32]:
from IPython.display import HTML, display

# Dán link bạn copy được vào giữa 2 dấu ngoặc kép ở dòng dưới:
tom_lizard_url = "https://media.tenor.com/4z6I_eTZanwAAAAj/screaming-tom-lizard.gif"

html_code = f"""
<div id="pet-container" style="position: relative; width: 100%; height: 180px; overflow: hidden; background-color: #e6f7ff; border-radius: 10px; border: 2px dashed #87cefa;">
    <h3 style="text-align: center; color: #555; font-family: sans-serif; margin-top: 10px;">Drama ập tới và Tom đang chạy trốn 🦎💦</h3>

    <img id="pet" src="{tom_lizard_url}" style="position: absolute; height: 90px; top: 60px; left: 0px;">
</div>

<script>
    let container = document.getElementById('pet-container');
    let pet = document.getElementById('pet');
    let pos = 0;
    let direction = 1;
    let speed = 4; // Tốc độ chạy cuống cuồng

    setInterval(function() {{
        let width = container.offsetWidth;
        // Chiều ngang ảnh khoảng 90px, đụng viền thì quay đầu
        if (pos > width - 90) direction = -1;
        if (pos < 0) direction = 1;

        pos += direction * speed;
        pet.style.left = pos + 'px';

        // Lật ảnh để Tom nhìn đúng hướng đang chạy
        pet.style.transform = direction === -1 ? 'scaleX(-1)' : 'scaleX(1)';
    }}, 20); // Cập nhật hình ảnh mỗi 20 mili-giây
</script>
"""

display(HTML(html_code))

In [36]:
from IPython.display import HTML, display

# Dán link bạn copy được vào giữa 2 dấu ngoặc kép ở dòng dưới:
tom_lizard_url = "https://media.tenor.com/45SXyw-S0VQAAAAi/bird-parrot.gif"

html_code = f"""
<div id="pet-container" style="position: relative; width: 100%; height: 180px; overflow: hidden; background-color: #e6f7ff; border-radius: 10px; border: 2px dashed #87cefa;">
    <h3 style="text-align: center; color: #555; font-family: sans-serif; margin-top: 10px;">Drama ập tới và Tom đang chạy trốn 🦎💦</h3>

    <img id="pet" src="{tom_lizard_url}" style="position: absolute; height: 90px; top: 60px; left: 0px;">
</div>

<script>
    let container = document.getElementById('pet-container');
    let pet = document.getElementById('pet');
    let pos = 0;
    let direction = 1;
    let speed = 4; // Tốc độ chạy cuống cuồng

    setInterval(function() {{
        let width = container.offsetWidth;
        // Chiều ngang ảnh khoảng 90px, đụng viền thì quay đầu
        if (pos > width - 90) direction = -1;
        if (pos < 0) direction = 1;

        pos += direction * speed;
        pet.style.left = pos + 'px';

        // Lật ảnh để Tom nhìn đúng hướng đang chạy
        pet.style.transform = direction === -1 ? 'scaleX(-1)' : 'scaleX(1)';
    }}, 20); // Cập nhật hình ảnh mỗi 20 mili-giây
</script>
"""

display(HTML(html_code))

In [37]:
#Tao pandas
import pandas as pd
a=pd.Series([1.,2.,3.])
print(a)
print('first values:', a[0])
b=pd.Series([1.,2.,3.], index=['a','b','c'])
print(b)
print('first values:', b['a'])
#tao pandas series tu dictionary
calories={"day1":420, "day2":380, "day3":390}
myvar=pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
first values: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
first values: 1.0
day1    420
day2    380
day3    390
dtype: int64


In [43]:
#numpy-->pandas
import pandas as pd
import numpy as np
h=np.array([[1,2], [3,4]])
df_h=pd.DataFrame(h)
print('DataFramed:\n',df_h)
#pandas-->numpy
numpy_h=np.array(df_h)
print('Numpy array:\n',numpy_h)

DataFramed:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [44]:
dic ={'Name':['John', 'Smith'], 'Age':[30,40]}
df_dic=pd.DataFrame(dic)
print(df_dic)


    Name  Age
0   John   30
1  Smith   40


In [46]:
r=np.random.randn(20,4)
df=pd.DataFrame(r,columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())#in 5 dong dau tien

        so1       so2       so3       so4
0  0.250052  0.131289  0.801416 -1.342791
1 -1.571579  1.108942  1.756219  2.071584
2 -2.125089 -1.033706 -0.365631 -1.594622
3  1.330337  0.353380 -1.282531  0.901592
4 -0.461305 -0.479953  0.562759  0.078900


In [47]:
r= np.random.randn(20,4)
df=pd.DataFrame(r,columns=['so1', 'so2', 'so3', 'so4'])
print(df.tail())#in 5 dong dau tien

print('Chon con so1\n', df['so1'])

print('Chon nhieu dong\n',df[0:3])

print('Chon nhieu cot\n',df[['so1', 'so3']])

print('Chon nhieu dong, nhieu cot\n', df.iloc[:3, :2])

df = df.drop(columns=['so1', 'so4'])
print(df)

         so1       so2       so3       so4
15  1.237112  0.691731 -0.680208  1.414287
16 -1.042961  0.295467 -1.279019 -0.010490
17 -0.087279 -0.198302 -0.367365 -2.007773
18  0.419038 -0.940754  1.494034  0.722167
19  0.543796  0.845426  2.139337 -1.160507
Chon con so1
 0    -2.328881
1    -0.256893
2     2.886201
3    -0.064571
4    -0.227224
5     0.403167
6     3.739389
7    -1.132703
8     0.488737
9     0.319166
10    1.372809
11   -0.874854
12   -0.337724
13    1.006616
14   -2.817262
15    1.237112
16   -1.042961
17   -0.087279
18    0.419038
19    0.543796
Name: so1, dtype: float64
Chon nhieu dong
         so1       so2       so3       so4
0 -2.328881  0.379434  0.410353  0.295523
1 -0.256893 -1.382874  0.513571 -1.806387
2  2.886201  0.615325  0.016557  0.237268
Chon nhieu cot
          so1       so3
0  -2.328881  0.410353
1  -0.256893  0.513571
2   2.886201  0.016557
3  -0.064571  0.178805
4  -0.227224 -0.852588
5   0.403167 -1.227005
6   3.739389  0.493090
7  -1.132703  0.0

In [48]:
from IPython.display import HTML, display

# Dán link bạn copy được vào giữa 2 dấu ngoặc kép ở dòng dưới:
tom_lizard_url = "https://media.tenor.com/45SXyw-S0VQAAAAi/bird-parrot.gif"

html_code = f"""
<div id="pet-container" style="position: relative; width: 100%; height: 180px; overflow: hidden; background-color: #e6f7ff; border-radius: 10px; border: 2px dashed #87cefa;">
    <h3 style="text-align: center; color: #555; font-family: sans-serif; margin-top: 10px;">Drama ập tới và Tom đang chạy trốn 🦎💦</h3>

    <img id="pet" src="{tom_lizard_url}" style="position: absolute; height: 90px; top: 60px; left: 0px;">
</div>

<script>
    let container = document.getElementById('pet-container');
    let pet = document.getElementById('pet');
    let pos = 0;
    let direction = 1;
    let speed = 4; // Tốc độ chạy cuống cuồng

    setInterval(function() {{
        let width = container.offsetWidth;
        // Chiều ngang ảnh khoảng 90px, đụng viền thì quay đầu
        if (pos > width - 90) direction = -1;
        if (pos < 0) direction = 1;

        pos += direction * speed;
        pet.style.left = pos + 'px';

        // Lật ảnh để Tom nhìn đúng hướng đang chạy
        pet.style.transform = direction === -1 ? 'scaleX(-1)' : 'scaleX(1)';
    }}, 20); // Cập nhật hình ảnh mỗi 20 mili-giây
</script>
"""

display(HTML(html_code))

In [49]:
#Nối 2 DataFrame
df1 = pd.DataFrame({'Name': ['John', 'Smith', 'Paul'],
                    'Age': [25, 30, 50]}, index=[0, 1, 2])

df2 = pd.DataFrame({'Name': ['Adam', 'Smith'],
                    'Age': [26, 11]}, index=[3, 4])

df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

# Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicate values in DataFrame\n', df_concat.drop_duplicates('Name'))

# Sắp xếp theo cột
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

# Đổi tên cột
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)


Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicate values in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


In [50]:
import pandas as pd


path = '/content/sample_data/california_housing_test.csv'


df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)


print(df_csv.head())


print(df_csv.shape)



   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  
(3000, 9)


In [53]:
a=np.random.randint(0,21, size=(3,3))
print(a)
print("Tất cả phần tử đều khác 0 (np.all):", np.all(a != 0))


[[11 19 20]
 [ 2  3  8]
 [ 5 17  5]]
Tất cả phần tử đều khác 0 (np.all): True


In [54]:
a=np.random.randint(0,21, size=(3,3))
print(a)
print("Tồn tại ít nhất một phần tử khác 0 (np.any):", np.any(a != 0))

[[ 5  7  4]
 [12 10  4]
 [ 0  8  7]]
Tồn tại ít nhất một phần tử khác 0 (np.any): True


x > y (greater): [ True False False]
x >= y (greater_equal): [ True False False]
x < y (less): [False  True  True]
x <= y (less_equal): [False  True  True]


In [7]:
import numpy as np

# Tạo mảng gồm 10 số 1
ones_array = np.ones(10)

# Tạo mảng gồm 10 số 0
zeros_array = np.zeros(10)

# Tạo mảng gồm 10 số 5
fives_array = np.full(10, 5.)

# Nối các mảng lại với nhau
result_array = np.hstack((ones_array))
result_array1 = np.hstack((zeros_array))
result_array2 = np.hstack((fives_array))
print(result_array)
print(result_array1)
print(result_array2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [10]:
b=np.arange(30, 71, 2)
print(b)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [14]:
import numpy as np

# Tạo ma trận đơn vị 3x3
identity_matrix = np.identity(3)
print("Ma trận đơn vị 3x3:")
print(identity_matrix)

Ma trận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
import numpy as np

# Tạo mảng 10 phần tử trong khoảng [15, 55]
random_array = np.random.randint(15, 56, size=10)
print("Mảng gốc:", random_array)

# In các giá trị ngoại trừ phần tử đầu và cuối
print("Các giá trị ngoại trừ phần tử đầu và cuối:", random_array[1:-1])

Mảng gốc: [28 42 44 47 33 42 37 25 38 33]
Các giá trị ngoại trừ phần tử đầu và cuối: [42 44 47 33 42 37 25 38]


In [16]:
import numpy as np

# Tạo mảng 20 phần tử trong khoảng [0, 20]
arr = np.random.randint(0, 21, size=20)
print("Mảng gốc:", arr)

# Đổi dấu những số nằm trong khoảng [9, 15]
arr[(arr >= 9) & (arr <= 15)] *= -1

print("Mảng sau khi đổi dấu:", arr)

Mảng gốc: [12  2  3 15  1 18  3 19  9  8  7  1 19  7 18 19 10 20 19 19]
Mảng sau khi đổi dấu: [-12   2   3 -15   1  18   3  19  -9   8   7   1  19   7  18  19 -10  20
  19  19]


In [17]:
import numpy as np

#9
matrix_3x4 = np.random.randint(10, 22, size=(3, 4))
print("Ma trận 3x4:")
print(matrix_3x4)

Ma trận 3x4:
[[18 10 12 15]
 [17 16 16 17]
 [21 12 13 14]]


In [18]:
import numpy as np

# Tạo ma trận 10x10 với tất cả các phần tử bằng 0
matrix_10x10 = np.zeros((10, 10), dtype=int)

# Đặt các phần tử ở biên bằng 1
matrix_10x10[0, :] = 1  # Hàng đầu tiên
matrix_10x10[-1, :] = 1 # Hàng cuối cùng
matrix_10x10[:, 0] = 1  # Cột đầu tiên
matrix_10x10[:, -1] = 1 # Cột cuối cùng

print("Ma trận 10x10 với biên là 1 và bên trong là 0:")
print(matrix_10x10)

Ma trận 10x10 với biên là 1 và bên trong là 0:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [60]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

url = 'https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/main/Data/covid19/countries-aggregated_csv.csv'
df = pd.read_csv(url)

print("Kích thước dữ liệu ban đầu:", df.shape)

df = df.dropna()

df = df.drop(columns=['Date'])

target_column = 'Deaths'
X = df.drop(columns=[target_column])

y = df[target_column] / 1000.0

X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)

X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1, 1)

print("\n--- Hoàn tất tiền xử lý ---")
print("Kích thước X_train tensor:", X_train_tensor.shape)
print("Kích thước y_train tensor:", y_train_tensor.shape)

Kích thước dữ liệu ban đầu: (39480, 5)

--- Hoàn tất tiền xử lý ---
Kích thước X_train tensor: torch.Size([31206, 189])
Kích thước y_train tensor: torch.Size([31206, 1])
